apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: my-backend-app:latest  # Update with your backend image
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: DB_HOST
              value: sqlserver-service
            - name: DB_PORT
              value: "1433"
            - name: DB_USER
              value: "sa"
            - name: DB_PASSWORD
              value: "YourStrong!Passw0rd"
            - name: DB_NAME
              value: "your_database"
