apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: my-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
