apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: my-frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32356
  type: NodePort
