apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # Service port (cluster-internal)
      targetPort: 3000  # Pod port (matches your container)
      nodePort: 32356   # Must be between 30000-32767
