apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default  # Change this if using another namespace
type: Opaque
data:
  DB_USER: bXlfZGItdXNlcg==  # Base64 encoded
  DB_PASSWORD: c3VwZXJzZWNyZXQ=  # Base64 encoded
  JWT_SECRET: c2VjcmV0a2V5  # Base64 encoded
