apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  DB_USER: c2E=
  DB_PASSWORD: WW91clN0cm9uZyFQYXNzdzByZDEyMw==
  MSSQL_SA_PASSWORD: WW91clN0cm9uZyFQYXNzdzByZA==  # Base64-encoded SA password
  JWT_SECRET: c2VjcmV0a2V5
