apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_USER: bXlfZGItdXNlcg==  # Base64 encoded
  DB_PASSWORD: c3VwZXJzZWNyZXQ=  # Base64 encoded
  JWT_SECRET: c2VjcmV0a2V5  # Base64 encoded
