apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlserver-configmap  # Changed to match deployment reference
  namespace: default  # Change to your actual namespace if needed
data:
  MSSQL_PID: "Developer"
  ACCEPT_EULA: "Y"
  MSSQL_LCID: "1033"
  MSSQL_COLLATION: "SQL_Latin1_General_CP1_CI_AS"
  MSSQL_MEMORY_LIMIT_MB: "2048"
  MSSQL_TCP_PORT: "1433"
  MSSQL_AGENT_ENABLED: "true"
  MSSQL_SSL_ENABLED: "0"  # Disables SSL encryption