apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  labels:
    app: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
      - name: install-mssql-tools
        image: ubuntu:20.04
        command:
          - /bin/sh
          - -c
          - |
            apt-get update && apt-get install -y curl apt-transport-https gnupg &&
            curl -sSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add - &&
            echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main" > /etc/apt/sources.list.d/mssql-release.list &&
            apt-get update &&
            ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
        securityContext:
          runAsUser: 10001
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        envFrom:
        - configMapRef:
            name: sqlserver-config
        - secretRef:
            name: sqlserver-secret
        securityContext:
          runAsUser: 10001
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q 'SELECT 1'"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q 'SELECT 1'"
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: sqlserver-pvc
