apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      initContainers:
        - name: install-mssql-tools
          image: mcr.microsoft.com/mssql-tools:latest
          command: ["sh", "-c", "cp -r /opt/mssql-tools /mnt/mssql-tools"]
          volumeMounts:
            - mountPath: /mnt/mssql-tools
              name: mssql-tools
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          envFrom:
            - secretRef:
                name: app-secrets
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: mssql-storage
            - mountPath: /opt/mssql-tools
              name: mssql-tools
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: sqlserver-pvc
        - name: mssql-tools
          emptyDir: {}
