apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  labels:
    app: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
      - name: volume-permission-fix
        image: mcr.microsoft.com/mssql/server:2019-CU16-ubuntu-20.04
        command: ["bash", "-c", "chown -R 10001:10001 /var/opt/mssql"]
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-CU16-ubuntu-20.04
        ports:
        - containerPort: 1433
        envFrom:
        - configMapRef:
            name: sqlserver-configmap
        - secretRef:
            name: sqlserver-secret
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          exec:
            command:
              - /opt/mssql-tools/bin/sqlcmd
              - -S
              - localhost
              - -U
              - sa
              - -P
              - "$(SA_PASSWORD)"
              - -Q
              - "SELECT 1"
          initialDelaySeconds: 120  # Wait longer before first check
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: sqlserver-pvc