apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  labels:
    app: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
      - name: init-sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        command:
          - /bin/sh
          - -c
          - |
            echo "Init SQL Server Container"
        securityContext:
          runAsUser: 10001
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        envFrom:
        - configMapRef:
            name: sqlserver-config
        - secretRef:
            name: sqlserver-secret
        securityContext:
          runAsUser: 10001
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q 'SELECT 1'"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q 'SELECT 1'"
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: sqlserver-pvc
